### ISSUE TITLE
Software rendering

### ISSUE THREAD

**Issue by Dyrewulfe** [a1studmuffin/Cataclysm-DDA-Android#2]
There are 2 issues currently remaining to stabilize software rendering:

1. If the screen is locked prior to the application being paused(home screen, switch apps, phone call, etc.), then the rendering will freeze.

2. Not nearly as serious, but the screen will black out after orientation changes, until the app is paused and then resumed.

**Comment by Dyrewulfe** [comment]
3. The software renderer doesn't properly update the screen in portrait, at least on my device. It seems that it's only related to text. In my case, the main menu is cut off on the right side(or simply doesn't update after the screen is rotated), as well the sidebar when in game. The minimap still works though.

Is there a reason to support portrait orientation at this time? Without support for re-arranging ui elements like the sidebar, it seems a rather cramped and inconvenient way to play. I don't recall seeing any screenshots in potrait mode from players, barring ones related to showstopping bugs.

**Comment by a1studmuffin** [comment]
I figured it might be good for phablets if you wanted to play with the virtual keyboard always visible instead of shortcuts? But yeah haven't seen many screenshots indicating this so if it's road blocking the software renderer we could look at disabling it (and see if anyone complains). It is a beta test after all. ;)

**Comment by Dyrewulfe** [comment]
Honestly, dynamic rotation is the only thing causing trouble now(at least in regards to rotation). And, I think there's at least one device out  there with a hardware keyboard and a square screen(it's a Blackberry, iirc). Something like that would DEFINITELY want the option to use potrait mode. Also, some oddball devices have a reversed landscape orientation by default, so we'd want that option as well.

We could make changing orientation a "requires restart", which it honestly shouldn't, but at least that hides the issue from the user. And scrap using the sensor, of course.

**Comment by Dyrewulfe** [comment]
Something else I've noticed with dynamic rotation, is that repeatedly rotating the screen can cause strange display errors, e.g. the window will display offset and distorted. Might be another sdl bug... Sigh.

**Comment by a1studmuffin** [comment]
With locked orientations, I think there's still an issue with the code at the moment where if you launch an app in say portrait, but the app is set to lock to landscape, it will still perform an initial rotation on startup which may still break the software renderer... so to avoid this you'd need to be holding the device in landscape when you run the app. I think the fix for this will involve forcing the device into landscape during the Java startup phase (before the C++ SDL side begins).

**Comment by Dyrewulfe** [comment]
Another option could be to glean the rotation setting from the options.json at that point. A little extra work, but if someone really wants potrait orientation, that serves them as well.

**Comment by Dyrewulfe** [comment]
I've made progress with the rotation issue. Not losing the screen entirely anymore, but the clipping rectangle is totally borked after a rotation. If my luck holds out, I'll have that licked within the hour. I seem to be on a roll tonight.

**Comment by Dyrewulfe** [comment]
Got this one figured out too.
