### ISSUE TITLE
Bluetooth keyboard connectivity issue (minor)

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#4]
This minor issue was reported on the forums. 

Repro steps:
- Connect a bluetooth keyboard
- Start a game
- While ingame, switch focus to an other app ( for me, tested with : return to desktop or switch to web navigator )
- Return to game 
- At this point any key except directions and escape don't work ( shortcut modifications not impacted. EDIT : I mean the modifications done to shorcut are not reverted, but keypress dont work )

To correct user-side :
- Just disconnect and reconnect bluetooth keyboard, thats fine
For this minor problem i have to mention the option "virtual keyboard" in "android" tab is set to auto .

**Comment by Zeropol** [comment]
More precisely to correct userside : press the 'android back button' once no need to disconnect/reconnect keyboard.

**Comment by Dyrewulfe** [comment]
> More precisely to correct userside : press the 'android back button' once no need to disconnect/reconnect keyboard.

That makes this easier to solve, then. Thank you for the info.

**Comment by Dyrewulfe** [comment]
Unassigned myself. The method I planned to test this with is not working. So, I have no means to test the results.

Edit: Actually, it turns out I can test this. It also afffects my USB keyboard.

**Comment by Zeropol** [comment]
The fact some keys ( directions, escape, enter ) still work when the app regain focus could mean the keyboard is wrongly detected as gamepad ( until the android back button is pressed ).

**Comment by Dyrewulfe** [comment]
This appears to be either an SDL or Android issue, or both. The issue resolves itself on back key down, not up. That's the behavior when clearing an on-screen keyboard. So, I suspect Android itself is the culprit here, saying there's an IME on-screen, when there isn't. I'll try to find a workaround, but I'm not feeling too confident on this one.

I believe SDL is seeking unicode input from this dummy IME. The keys that still work do so because they're read differently and send different events that aren't tied to the SDL2 unicode implementation.

**Comment by Dyrewulfe** [comment]
Okay, got this one fixed, too.
